### ISSUE TITLE
meinberlin build broken on master

### ISSUE THREAD

**Issue by pallix** [liqd/adhocracy3#2158]
```
src/meinberlin/meinberlin/build/js/Adhocracy.d.ts(1,1): error TS6053: File 'src/meinberlin/meinberlin/build/lib/DefinitelyTyped/requirejs/require.d.ts' not found.
src/meinberlin/meinberlin/build/js/Adhocracy.d.ts(2,1): error TS6053: File 'src/meinberlin/meinberlin/build/lib/DefinitelyTyped/angularjs/angular.d.ts' not found.
src/meinberlin/meinberlin/build/js/Adhocracy.d.ts(3,1): error TS6053: File 'src/meinberlin/meinberlin/build/lib/DefinitelyTyped/lodash/lodash.d.ts' not found.
src/meinberlin/meinberlin/build/js/Adhocracy.d.ts(4,1): error TS6053: File 'src/meinberlin/meinberlin/build/lib/DefinitelyTyped/modernizr/modernizr.d.ts' not found.
src/meinberlin/meinberlin/build/js/Adhocracy.d.ts(5,1): error TS6053: File 'src/meinberlin/meinberlin/build/lib/DefinitelyTyped/moment/moment.d.ts' not found.
src/meinberlin/meinberlin/build/js/Adhocracy.d.ts(6,1): error TS6053: File 'src/meinberlin/meinberlin/build/lib/DefinitelyTyped/leaflet/leaflet.d.ts' not found.
javascript: Non zero exit code (2) while running command.
```

**Comment by Johnschmidfront** [comment]
probably caused by #2141

**Comment by Johnschmidfront** [comment]
I had the same error. Then I removed `src/meinberlin/meinberlin/build/js/Adhocracy.d.ts` and it worked fine.

**Comment by xi** [comment]
I can verify that removing Adhocracy.d.ts fixes the issue.

**Comment by joka** [comment]
I had an similar error again with all extension packages except mercator: 

  Installing javascript.
   javascript: Running '/home/joka/dev/adhocracy-3/bin/node /home/joka/dev/adhocracy-3/bin/tsc -m umd -  -      sourcemap --pretty src/spd/spd/build/js/Adhocracy*.ts'

    1 /// <reference path="../../../lib/DefinitelyTyped/jasmine/jasmine.d.ts" />
     ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

     src/spd/spd/build/js/Packages/Comment/AdapterSpec.d.ts(1,1): error TS6053: File     '/home/joka/dev/adhocracy-3/src/spd/spd/build/lib/DefinitelyTyped/jasmine/jasmine.d.ts' not found.


Removing Adhocracy.ts  and Adhocracy.d.ts helped.

However, if this is a general problem caused by the build script,  can we fix this somehow?

**Comment by xi** [comment]
The issue is caused by stale `*.d.ts` files that reference files that no longer exist. These `*.d.ts*` files are no longer generated (see a71c84ffb8e1db2d594ae11aca534182a0672ece), so the problem is kind of fixed already. You just have to remove the build directory once. This is inconvenient, but it does not justify writing custom code IMHO.
