### PR TITLE
make sheet arguments optional if not create_mandatory

### PR DESCRIPTION
**Pull request by xi**
The build is currently broken with the follwing error message:

```
/home/tobib/a3/a3/bin/tsc --module commonjs --sourcemap src/mercator/mercator/build/js/mkResources.ts
/home/tobib/a3/a3/bin/node src/mercator/mercator/build/js/mkResources.js src/mercator/mercator/build/meta_api.json src/mercator/mercator/build/js
Updating javascript.
javascript: Running /home/tobib/a3/a3/bin/node /home/tobib/a3/a3/bin/tsc -m umd -d --sourcemap src/mercator/mercator/build/js/Adhocracy*.ts
src/mercator/mercator/build/js/Packages/Document/Document.ts(219,86): error TS2345: Argument of type '{ picture: string; }' is not assignable to parameter of type '{ picture: string; picture_description: string; external_picture_url: string; }'.
  Property 'picture_description' is missing in type '{ picture: string; }'.
src/mercator/mercator/build/js/Packages/Document/Document.ts(322,86): error TS2345: Argument of type '{ picture: string; }' is not assignable to parameter of type '{ picture: string; picture_description: string; external_picture_url: string; }'.
  Property 'picture_description' is missing in type '{ picture: string; }'.
src/mercator/mercator/build/js/Packages/Image/Image.ts(81,72): error TS2345: Argument of type '{ picture: string; }' is not assignable to parameter of type '{ picture: string; picture_description: string; external_picture_url: string; }'.
  Property 'picture_description' is missing in type '{ picture: string; }'.
src/mercator/mercator/build/js/Packages/Mercator/2016/Proposal/Proposal.ts(265,79): error TS2345: Argument of type '{ picture: string; }' is not assignable to parameter of type '{ picture: string; picture_description: string; external_picture_url: string; }'.
  Property 'picture_description' is missing in type '{ picture: string; }'.
```

The issue was probably caused by #2024, but the error seems to be in the TypeScript code that is automatically generated from the meta_api: Some arguments to the sheet constructor were not marked as optional.

### CODE REVIEW

**Comment by Johnschmidfront** [comment]
looks good.
